services:
  postgres:
    image: postgres:16-alpine
    container_name: bloghub-postgres
    environment:
      POSTGRES_DB: bloghub_dev
      POSTGRES_USER: bloghub_user
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloghub_user -d bloghub_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: