services:
  postgres:
    image: postgres:16-alpine
    container_name: bloghub-postgres
    environment:
      POSTGRES_DB: bloghub_dev
      POSTGRES_USER: bloghub_user
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloghub_user -d bloghub_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: